2018-05-29 12:19:53,166 (7933/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2018-05-29 12:19:53,183 (7933/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/laixintao/.local/venvs/pgcli/lib/python3.6/site-packages/pgcli/main.py", line 416, in connect\n    raise e\n  File "/Users/laixintao/.local/venvs/pgcli/lib/python3.6/site-packages/pgcli/main.py", line 406, in connect\n    **kwargs)\n  File "/Users/laixintao/.local/venvs/pgcli/lib/python3.6/site-packages/pgcli/pgexecute.py", line 173, in __init__\n    self.connect()\n  File "/Users/laixintao/.local/venvs/pgcli/lib/python3.6/site-packages/pgcli/pgexecute.py", line 198, in connect\n    **kwargs)\n  File "/Users/laixintao/.local/venvs/pgcli/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/Users/laixintao/.local/venvs/pgcli/lib/python3.6/site-packages/pgcli/pgexecute.py", line 40, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  role "postgres" does not exist\n\n'
2018-05-29 12:21:46,991 (8041/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2018-05-29 12:22:38,233 (8041/MainThread) pgcli.pgexecute ERROR - sql: 'create database takachiho', error: ProgrammingError('permission denied to create database\n',)
2018-05-29 12:22:38,234 (8041/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/laixintao/.local/venvs/pgcli/lib/python3.6/site-packages/pgcli/pgexecute.py", line 319, in run\n    yield self.execute_normal_sql(sql) + (sql, True)\n  File "/Users/laixintao/.local/venvs/pgcli/lib/python3.6/site-packages/pgcli/pgexecute.py", line 355, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.ProgrammingError: permission denied to create database\n\n'
2018-05-29 12:23:10,268 (8090/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2018-05-29 12:31:28,961 (9019/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2018-05-29 12:31:28,977 (9019/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/laixintao/.local/venvs/pgcli/lib/python3.6/site-packages/pgcli/main.py", line 416, in connect\n    raise e\n  File "/Users/laixintao/.local/venvs/pgcli/lib/python3.6/site-packages/pgcli/main.py", line 406, in connect\n    **kwargs)\n  File "/Users/laixintao/.local/venvs/pgcli/lib/python3.6/site-packages/pgcli/pgexecute.py", line 173, in __init__\n    self.connect()\n  File "/Users/laixintao/.local/venvs/pgcli/lib/python3.6/site-packages/pgcli/pgexecute.py", line 198, in connect\n    **kwargs)\n  File "/Users/laixintao/.local/venvs/pgcli/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/Users/laixintao/.local/venvs/pgcli/lib/python3.6/site-packages/pgcli/pgexecute.py", line 40, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: could not connect to server: Connection refused\n\tIs the server running on host "mysql.takachiho.inc.alipay.net" (11.167.96.78) and accepting\n\tTCP/IP connections on port 5432?\n\n'
